# Check out https://hub.docker.com/_/node to select a new base image
FROM node:lts

# Some dependencies from package.json are installed from git
# RUN apt-get update && apt-get upgrade -y && apt-get install -y git python3 build-essential curl

# Use the same uid and gid as the host to avoid permission errors
# ARG UID
# ARG GID
# RUN usermod -u $UID node
# RUN groupmod -g $GID node
# Set to a non-root built-in user `node`
USER node

# Create app directory (with user `node`)
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY ./package.json .

RUN npm install

# ENTRYPOINT ["npm", "run", "start:dev"]
ENTRYPOINT [ "./wait-for-node.dev.sh" ]
